version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: proyecto
      MYSQL_USER: username
      MYSQL_PASSWORD: Password123/
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql