spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/proyecto
    username: username
    password: Password123/

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true